<?php


  
 function current_time_preprocess_html(&$variables){
  // kint("test");
  // $time= \Drupal::service("current_time.location");
  // kint($time);
  // kint($time->getCurrentTime());
  // kint($time->getTime());
}


/**
 * Implements hook_theme().
 */
function current_time_theme($existing, $type, $theme, $path) {
  return [
    'current_time_template' => [
    'variables' => ['test_var' => NULL, 'time' => NULL, 'country' => NULL, 'city' => NULL, ],

    ],
  ];
}